export const AUTHENTICATED = 'AUTHENTICATED';
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';
export const GET_MY_RESERVATIONS = 'GET_MY_RESERVATIONS';
export const FETCH_YACHTS_SUCCESS = "FETCH_YACHTS_SUCCESS";
export const FETCH_SINGLE_YACHT_SUCCESS = "FETCH_SINGLE_YACHT_SUCCESS";
